### ISSUE TITLE
unable to compile lua bindings

### ISSUE THREAD

**Issue by blshkv** [radare/radare2-bindings#173]
```
USE="lua" ebuild radare2-bindings-1.6.0.ebuild install 
 * radare2-bindings-1.6.0.tar.gz SHA256 SHA512 WHIRLPOOL size ;-) ...                                                              [ ok ]
>>> Unpacking source...
>>> Unpacking radare2-bindings-1.6.0.tar.gz to /var/tmp/portage/dev-libs/radare2-bindings-1.6.0/work
>>> Source unpacked in /var/tmp/portage/dev-libs/radare2-bindings-1.6.0/work
>>> Preparing source in /var/tmp/portage/dev-libs/radare2-bindings-1.6.0/work/radare2-bindings-1.6.0 ...
 * Applying 01_use_python_2.7.patch ...                                                                                            [ ok ]
>>> Source prepared.
>>> Configuring source in /var/tmp/portage/dev-libs/radare2-bindings-1.6.0/work/radare2-bindings-1.6.0 ...
./configure --prefix=/usr --build=x86_64-pc-linux-gnu --host=x86_64-pc-linux-gnu --mandir=/usr/share/man --infodir=/usr/share/info --datadir=/usr/share --sysconfdir=/etc --localstatedir=/var/lib --docdir=/usr/share/doc/radare2-bindings-1.6.0 --libdir=/usr/lib64 --enable=cxx,lua,python
==> Using valabind 0.10.0
==> Using swig 3.0.12
Checking valabind languages support...
 - python: yes
 - perl: yes
 - ruby: yes
 - lua: yes
 - go: no
 - java: yes
 - guile: yes
 - php5: no
 - node-ffi: yes
 - ctypes: yes
 - ocaml: no
 - cxx: yes (g++)
 - valac: no
Supported langs:
 - cxx
 - lua
 - python
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking target system type... x86_64-unknown-linux-gnu
using crosscompilation mode.
checking for working directories... current
using prefix '/usr'
checking for c compiler... x86_64-pc-linux-gnu-gcc
checking for c++ compiler... x86_64-pc-linux-gnu-g++
checking for valabind... /usr/bin/valabind
checking for swig... /usr/bin/swig
checking for g-ir-compiler... /usr/bin/g-ir-compiler
Using PKGCONFIG: pkg-config
checking pkg-config flags for r_core... yes
creating ./config.mk
cleaning temporally files... done

Final report:
 - PREFIX = /usr
 - HAVE_SWIG = 1
 - HAVE_VALABIND = 1
 - HAVE_GIRCOMPILER = 1
>>> Source configured.
>>> Compiling source in /var/tmp/portage/dev-libs/radare2-bindings-1.6.0/work/radare2-bindings-1.6.0 ...
make -j4 
make -C libr/lang/p
make[1]: Entering directory '/var/tmp/portage/dev-libs/radare2-bindings-1.6.0/work/radare2-bindings-1.6.0/libr/lang/p'
cc -march=native -O2 -pipe -I/usr/include/libr  -I/usr/include/texlua52    -c -o lua.o lua.c
cc python.c -march=native -O2 -pipe -I/usr/include/libr  -I/usr/include/texlua52  -I/usr/include/python2.7 -I/usr/include/python2.7  -march=native -O2 -pipe -fwrapv -DNDEBUG -DPYVER=2 -lpython2.7 -lpthread -ldl -lutil -lm -L/usr/lib  -lr_core -lr_io -lr_util -shared \
-Wl,-O1 -Wl,--as-needed -Wl,--hash-style=gnu  -lr_core -lr_io -lr_util -shared -fPIC -o lang_python2.so
lua.c: In function ‘init’:
lua.c:10:16: error: ‘PREFIX’ undeclared (first use in this function)
 #define LIBDIR PREFIX"/lib"
                ^
lua.c:97:20: note: in expansion of macro ‘LIBDIR’
  r_lua_file (NULL, LIBDIR"/radare2/"R2_VERSION"/radare.lua");
                    ^
lua.c:10:16: note: each undeclared identifier is reported only once for each function it appears in
 #define LIBDIR PREFIX"/lib"
                ^
lua.c:97:20: note: in expansion of macro ‘LIBDIR’
  r_lua_file (NULL, LIBDIR"/radare2/"R2_VERSION"/radare.lua");
                    ^
lua.c:10:22: error: expected ‘)’ before string constant
 #define LIBDIR PREFIX"/lib"
                      ^
lua.c:97:20: note: in expansion of macro ‘LIBDIR’
  r_lua_file (NULL, LIBDIR"/radare2/"R2_VERSION"/radare.lua");
                    ^
make[1]: *** [<builtin>: lua.o] Error 1
make[1]: Leaving directory '/var/tmp/portage/dev-libs/radare2-bindings-1.6.0/work/radare2-bindings-1.6.0/libr/lang/p'
make: *** [Makefile:46: all] Error 2
 * ERROR: dev-libs/radare2-bindings-1.6.0::pentoo failed (compile phase):
```

**Comment by radare** [comment]
Use r2pm or cd lua;make

**Comment by blshkv** [comment]
the previous version used to call it automatically.

Could you fix configure script so it would be possible to use a standard option such as:
```--enable=cxx,lua,python```

**Comment by radare** [comment]
you can already do this but the bug is in the makefile, not the configure

**Comment by radare** [comment]
should be fixed with valabind 1.3 and last r2b from git, reopen if not.

thanks for reporting!

**Comment by blshkv** [comment]
https://github.com/radare/radare2-bindings/commit/b8945c985e146de0a6a3b6bc9c667d081679cd1f
thanks, I'll apply it on the release.

**Comment by blshkv** [comment]
sorry, it did not help:
```
USE="lua" ebuild radare2-bindings-1.6.0.ebuild manifest clean install 
>>> Creating Manifest for /data/pentoo/pentoo/dev-libs/radare2-bindings
 * radare2-bindings-1.6.0.tar.gz SHA256 SHA512 WHIRLPOOL size ;-) ...                                                              [ ok ]
>>> Unpacking source...
>>> Unpacking radare2-bindings-1.6.0.tar.gz to /var/tmp/portage/dev-libs/radare2-bindings-1.6.0/work
>>> Source unpacked in /var/tmp/portage/dev-libs/radare2-bindings-1.6.0/work
>>> Preparing source in /var/tmp/portage/dev-libs/radare2-bindings-1.6.0/work/radare2-bindings-1.6.0 ...
 * Applying 01_use_python_2.7.patch ...                                                                                            [ ok ]
 * Applying 1.6.0-lua.patch ...                                                                                                    [ ok ]
>>> Source prepared.
>>> Configuring source in /var/tmp/portage/dev-libs/radare2-bindings-1.6.0/work/radare2-bindings-1.6.0 ...
./configure --prefix=/usr --build=x86_64-pc-linux-gnu --host=x86_64-pc-linux-gnu --mandir=/usr/share/man --infodir=/usr/share/info --datadir=/usr/share --sysconfdir=/etc --localstatedir=/var/lib --docdir=/usr/share/doc/radare2-bindings-1.6.0 --libdir=/usr/lib64 --enable=cxx,lua,python
==> Using valabind 0.10.0
==> Using swig 3.0.12
Checking valabind languages support...
 - python: yes
 - perl: yes
 - ruby: yes
 - lua: yes
 - go: no
 - java: yes
 - guile: yes
 - php5: no
 - node-ffi: yes
 - ctypes: yes
 - ocaml: no
 - cxx: yes (g++)
 - valac: no
Supported langs:
 - cxx
 - lua
 - python
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking target system type... x86_64-unknown-linux-gnu
using crosscompilation mode.
checking for working directories... current
using prefix '/usr'
checking for c compiler... x86_64-pc-linux-gnu-gcc
checking for c++ compiler... x86_64-pc-linux-gnu-g++
checking for valabind... /usr/bin/valabind
checking for swig... /usr/bin/swig
checking for g-ir-compiler... /usr/bin/g-ir-compiler
Using PKGCONFIG: pkg-config
checking pkg-config flags for r_core... yes
creating ./config.mk
cleaning temporally files... done

Final report:
 - PREFIX = /usr
 - HAVE_SWIG = 1
 - HAVE_VALABIND = 1
 - HAVE_GIRCOMPILER = 1
>>> Source configured.
>>> Compiling source in /var/tmp/portage/dev-libs/radare2-bindings-1.6.0/work/radare2-bindings-1.6.0 ...
make -j4 
make -C libr/lang/p
make[1]: Entering directory '/var/tmp/portage/dev-libs/radare2-bindings-1.6.0/work/radare2-bindings-1.6.0/libr/lang/p'
cc -march=native -O2 -pipe -I/usr/include/libr  -I/usr/include/texlua52    -c -o lua.o lua.c
lua.c: In function ‘init’:
lua.c:10:16: error: ‘PREFIX’ undeclared (first use in this function)
 #define LIBDIR PREFIX"/lib"
                ^
lua.c:97:20: note: in expansion of macro ‘LIBDIR’
  r_lua_file (NULL, LIBDIR"/radare2/"R2_VERSION"/radare.lua");
                    ^
lua.c:10:16: note: each undeclared identifier is reported only once for each function it appears in
 #define LIBDIR PREFIX"/lib"
                ^
lua.c:97:20: note: in expansion of macro ‘LIBDIR’
  r_lua_file (NULL, LIBDIR"/radare2/"R2_VERSION"/radare.lua");
                    ^
lua.c:10:22: error: expected ‘)’ before string constant
 #define LIBDIR PREFIX"/lib"
                      ^
lua.c:97:20: note: in expansion of macro ‘LIBDIR’
  r_lua_file (NULL, LIBDIR"/radare2/"R2_VERSION"/radare.lua");
                    ^
make[1]: *** [<builtin>: lua.o] Error 1
make[1]: Leaving directory '/var/tmp/portage/dev-libs/radare2-bindings-1.6.0/work/radare2-bindings-1.6.0/libr/lang/p'
make: *** [Makefile:46: all] Error 2
 * ERROR: dev-libs/radare2-bindings-1.6.0::pentoo failed (compile phase):
 *   emake failed
 * 
 * If you need support, post the output of `emerge --info '=dev-libs/radare2-bindings-1.6.0::pentoo'`,
 * the complete build log and the output of `emerge -pqv '=dev-libs/radare2-bindings-1.6.0::pentoo'`.
 * The complete build log is located at '/var/tmp/portage/dev-libs/radare2-bindings-1.6.0/temp/build.log'.
 * The ebuild environment file is located at '/var/tmp/portage/dev-libs/radare2-bindings-1.6.0/temp/environment'.
 * Working directory: '/var/tmp/portage/dev-libs/radare2-bindings-1.6.0/work/radare2-bindings-1.6.0'
 * S: '/var/tmp/portage/dev-libs/radare2-bindings-1.6.0/work/radare2-bindings-1.6.0'
```

**Comment by blshkv** [comment]
sorry, it is not fixed for me. Could you open the bug and check again:
```
USE="lua" ebuild radare2-bindings-1.6.0.ebuild manifest clean install     
>>> Creating Manifest for /data/pentoo/pentoo/dev-libs/radare2-bindings
 * radare2-bindings-1.6.0.tar.gz SHA256 SHA512 WHIRLPOOL size ;-) ...                                                              [ ok ]
>>> Unpacking source...
>>> Unpacking radare2-bindings-1.6.0.tar.gz to /var/tmp/portage/dev-libs/radare2-bindings-1.6.0/work
>>> Source unpacked in /var/tmp/portage/dev-libs/radare2-bindings-1.6.0/work
>>> Preparing source in /var/tmp/portage/dev-libs/radare2-bindings-1.6.0/work/radare2-bindings-1.6.0 ...
 * Applying 01_use_python_2.7.patch ...                                                                                            [ ok ]
 * Applying 1.6.0-lua.patch ...                                                                                                    [ ok ]
>>> Source prepared.
>>> Configuring source in /var/tmp/portage/dev-libs/radare2-bindings-1.6.0/work/radare2-bindings-1.6.0 ...
./configure --prefix=/usr --build=x86_64-pc-linux-gnu --host=x86_64-pc-linux-gnu --mandir=/usr/share/man --infodir=/usr/share/info --datadir=/usr/share --sysconfdir=/etc --localstatedir=/var/lib --docdir=/usr/share/doc/radare2-bindings-1.6.0 --libdir=/usr/lib64 --enable=cxx,lua,python
==> Using valabind 1.3
==> Using swig 3.0.12
Checking valabind languages support...
 - python: yes
 - perl: yes
 - ruby: yes
 - lua: yes
 - go: no
 - java: yes
 - guile: yes
 - php5: no
 - node-ffi: yes
 - ctypes: yes
 - ocaml: no
 - cxx: yes (g++)
 - valac: no
Supported langs:
 - cxx
 - lua
 - python
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking target system type... x86_64-unknown-linux-gnu
using crosscompilation mode.
checking for working directories... current
using prefix '/usr'
checking for c compiler... x86_64-pc-linux-gnu-gcc
checking for c++ compiler... x86_64-pc-linux-gnu-g++
checking for valabind... /usr/bin/valabind
checking for swig... /usr/bin/swig
checking for g-ir-compiler... /usr/bin/g-ir-compiler
Using PKGCONFIG: pkg-config
checking pkg-config flags for r_core... yes
creating ./config.mk
cleaning temporally files... done

Final report:
 - PREFIX = /usr
 - HAVE_SWIG = 1
 - HAVE_VALABIND = 1
 - HAVE_GIRCOMPILER = 1
>>> Source configured.
>>> Compiling source in /var/tmp/portage/dev-libs/radare2-bindings-1.6.0/work/radare2-bindings-1.6.0 ...
make -j4 
make -C libr/lang/p
make[1]: Entering directory '/var/tmp/portage/dev-libs/radare2-bindings-1.6.0/work/radare2-bindings-1.6.0/libr/lang/p'
cc -march=native -O2 -pipe -I/usr/include/libr  -I/usr/include/texlua52    -c -o lua.o lua.c
lua.c: In function ‘init’:
lua.c:10:16: error: ‘PREFIX’ undeclared (first use in this function)
 #define LIBDIR PREFIX"/lib"
                ^
lua.c:97:20: note: in expansion of macro ‘LIBDIR’
  r_lua_file (NULL, LIBDIR"/radare2/"R2_VERSION"/radare.lua");
                    ^
lua.c:10:16: note: each undeclared identifier is reported only once for each function it appears in
 #define LIBDIR PREFIX"/lib"
                ^
lua.c:97:20: note: in expansion of macro ‘LIBDIR’
  r_lua_file (NULL, LIBDIR"/radare2/"R2_VERSION"/radare.lua");
                    ^
lua.c:10:22: error: expected ‘)’ before string constant
 #define LIBDIR PREFIX"/lib"
                      ^
lua.c:97:20: note: in expansion of macro ‘LIBDIR’
  r_lua_file (NULL, LIBDIR"/radare2/"R2_VERSION"/radare.lua");
                    ^
make[1]: *** [<builtin>: lua.o] Error 1
make[1]: Leaving directory '/var/tmp/portage/dev-libs/radare2-bindings-1.6.0/work/radare2-bindings-1.6.0/libr/lang/p'
make: *** [Makefile:46: all] Error 2
 * ERROR: dev-libs/radare2-bindings-1.6.0::pentoo failed (compile phase):
 *   emake failed
 * 
 * If you need support, post the output of `emerge --info '=dev-libs/radare2-bindings-1.6.0::pentoo'`,
 * the complete build log and the output of `emerge -pqv '=dev-libs/radare2-bindings-1.6.0::pentoo'`.
 * The complete build log is located at '/var/tmp/portage/dev-libs/radare2-bindings-1.6.0/temp/build.log'.
 * The ebuild environment file is located at '/var/tmp/portage/dev-libs/radare2-bindings-1.6.0/temp/environment'.
 * Working directory: '/var/tmp/portage/dev-libs/radare2-bindings-1.6.0/work/radare2-bindings-1.6.0'
 * S: '/var/tmp/portage/dev-libs/radare2-bindings-1.6.0/work/radare2-bindings-1.6.0'
```

**Comment by blshkv** [comment]
ok, found a missing bit of the patch:

```
--- Makefile.orig       2017-08-03 10:01:53.000000000 +0800
+++ Makefile    2017-08-03 10:04:59.258412920 +0800
@@ -2,6 +2,7 @@
 include ../../../config.mk
 
 CFLAGS+=$(shell pkg-config --cflags r_core)
+CFLAGS+=-DPREFIX=\"${PREFIX}\"
 
 DUK_CFLAGS+=-Wall -DPREFIX=\"${PREFIX}\" -I. -Iduk

```


Thanks, FIXED!

**Comment by radare** [comment]
Uhm is this patch needed upstream?

**Comment by blshkv** [comment]
no, it is already there.
